@echo off
luac -o ../data/game.so ^
sys/load_core.lua ^
../data/scripts/load_gamesys.lua ^
../data/scripts/var.lua ^
../data/scripts/zdefine.lua ^
../data/scripts/util/eClass.lua ^
sys/load_sync.lua ^
../data/scripts/util/public/hApi.lua ^
../data/scripts/gamemsg.lua ^
../data/scripts/callback.lua ^
../data/scripts/androidfunc.lua ^
sys/load_tabs.lua ^
../data/scripts/util/public/luatools.lua ^
../data/scripts/util/public/functions.lua ^
../data/scripts/util/public/randommap.lua ^
../data/scripts/util/public/randmaproom_config.lua ^
../data/scripts/util/public/randmapenemy_config.lua ^
../data/scripts/util/public/randmapenemy.lua ^
../data/scripts/util/ui/ui.lua ^
../data/scripts/util/public/event.lua ^
../data/scripts/util/public/server.lua ^
../data/scripts/util/public/luanetcmddef.lua ^
../data/scripts/util/public/luasendnetcmd.lua ^
../data/scripts/util/public/luaonnetcmd.lua ^
../data/scripts/util/public/command.lua ^
../data/scripts/util/extern.lua ^
../data/scripts/util/public/VitrualController.lua ^
../data/scripts/util/public/randnameprocess.lua ^
../data/scripts/util/public/preloadtxtmanager.lua ^
../data/scripts/util/core/world.lua ^
../data/scripts/util/core/town.lua ^
../data/scripts/util/core/map.lua ^
../data/scripts/util/core/action.lua ^
../data/scripts/util/core/sceobj.lua ^
../data/scripts/util/core/unit.lua ^
../data/scripts/util/core/hero.lua ^
../data/scripts/util/core/effect.lua ^
../data/scripts/util/core/player.lua ^
../data/scripts/util/core/round.lua ^
../data/scripts/util/core/item.lua ^
../data/scripts/util/core/connect.lua ^
../data/scripts/ai/ai_calculate.lua ^
../data/scripts/logic/skill_API.lua ^
../data/scripts/iap/iap.lua ^
../data/scripts/gameserver/gameserver.lua ^
../data/scripts/gameserver/luaonnetcmd.lua ^
../data/scripts/gameserver/luasendnetcmd.lua ^
../data/scripts/gameserver/review.lua ^
../data/scripts/gameserver/autologin.lua ^
../data/scripts/actiontree/actiontreemanager.lua ^
../data/scripts/actiontree/blackdragon.lua ^
../data/scripts/actiontree/roboticarm.lua ^
../data/scripts/gamemanager.lua ^
../data/scripts/pvpserver/luaonnetcmd.lua ^
../data/scripts/pvpserver/luasendnetcmd.lua ^
../data/scripts/pvpserver/pvpserver.lua ^
../data/scripts/groupserver/var_define.lua ^
../data/scripts/groupserver/luaonnetcmd.lua ^
../data/scripts/groupserver/luasendnetcmd.lua ^
../data/scripts/groupserver/groupserver.lua ^
../data/scripts/util/public/hotfix.lua ^
../data/scripts/util/public/recordgamedata.lua ^
../data/scripts/util/public/unlock_manager.lua ^
../data/scripts/util/public/move_equip.lua ^
../data/scripts/util/ui/uiGame.lua ^
../data/scripts/util/ui/uiTemplate.lua ^
../data/scripts/util/ui/uiSkill.lua ^
../data/scripts/util/ui/uiCreate.lua ^
../data/scripts/util/ui/uiInit.lua ^
../data/scripts/util/ui/battlefieldoprfrm.lua ^
../data/scripts/util/ui/uiHero.lua ^
../data/scripts/util/ui/talkfrm.lua ^
../data/scripts/util/ui/worldrank.lua ^
../data/scripts/util/ui/herocardfrm.lua ^
../data/scripts/util/ui/sysmenu.lua ^
../data/scripts/util/ui/systmenu_mainbase.lua ^
../data/scripts/util/ui/system_commentmanage.lua ^
../data/scripts/util/ui/system_behaviorstatistics.lua ^
../data/scripts/util/ui/privacyandprotocol.lua ^
../data/scripts/util/ui/errorfram.lua ^
../data/scripts/util/ui/playercard.lua ^
../data/scripts/util/ui/itemitp.lua ^
../data/scripts/util/ui/msgtipfrm.lua ^
../data/scripts/util/ui/rewardfrm.lua ^
../data/scripts/util/ui/rewardfrmex.lua ^
../data/scripts/util/ui/selectedhero.lua ^
../data/scripts/util/ui/buyherocardfrm.lua ^
../data/scripts/util/ui/floatnumberBF.lua ^
../data/scripts/util/ui/playercardherofrm.lua ^
../data/scripts/util/ui/buyitemfailfrm.lua ^
../data/scripts/util/ui/giftfrm.lua ^
../data/scripts/util/ui/lua_inputfrm.lua ^
../data/scripts/util/ui/InAppPurchaseTipFrm.lua ^
../data/scripts/util/ui/InAppPurchaseTipFrm_Diablo.lua ^
../data/scripts/util/ui/InAppPurchaseTipFrm_Gift.lua ^
../data/scripts/util/ui/InAppPurchaseTipFrm_Equip.lua ^
../data/scripts/util/ui/uiTgrTalk.lua ^
../data/scripts/util/ui/battlefieldskillbook.lua ^
../data/scripts/util/ui/playergiftbagfrm.lua ^
../data/scripts/util/ui/levelupfrm.lua ^
../data/scripts/util/ui/recommendfrm.lua ^
../data/scripts/util/ui/weekstarhero.lua ^
../data/scripts/util/ui/debugfrm.lua ^
../data/scripts/util/ui/buyfustone.lua ^
../data/scripts/util/ui/buygiftitemfrm.lua ^
../data/scripts/util/ui/gamecoinfrm.lua ^
../data/scripts/util/ui/phone_main_menu.lua ^
../data/scripts/util/ui/phone_selectemap.lua ^
../data/scripts/util/ui/phone_selectemapdragon.lua ^
../data/scripts/util/ui/phone_selectmap_new.lua ^
../data/scripts/util/ui/phone_selectmap_new_temp.lua ^
../data/scripts/util/ui/phone_totalsettlement.lua ^
../data/scripts/util/ui/phone_maindotafrm.lua ^
../data/scripts/util/ui/phone_mygift.lua ^
../data/scripts/util/ui/phone_myherocardfrm.lua ^
../data/scripts/util/ui/phone_myherocardfrm_guide.lua ^
../data/scripts/util/ui/phone_mymedal.lua ^
../data/scripts/util/ui/phone_tacticcardfrm_guide.lua ^
../data/scripts/util/ui/phone_battlefieldoprfrm.lua ^
../data/scripts/util/ui/phone_itemfrm.lua ^
../data/scripts/util/ui/phone_itemfrm_RedEquip.lua ^
../data/scripts/util/ui/phone_itemfrm_Mini.lua ^
../data/scripts/util/ui/phone_itemfrm_Mini_RedEquip.lua ^
../data/scripts/util/ui/phone_taskfrm.lua ^
../data/scripts/util/ui/phone_signinfrm.lua ^
../data/scripts/util/ui/phone_activityfrm.lua ^
../data/scripts/util/ui/phone_achievementfrm.lua ^
../data/scripts/util/ui/phone_taskfrm_guide.lua ^
../data/scripts/util/ui/phone_dlcmapfrm.lua ^
../data/scripts/util/ui/phone_dragontalkfrm.lua ^
../data/scripts/util/ui/phone_pvpfrm.lua ^
../data/scripts/util/ui/phone_pvpfrm_endless.lua ^
../data/scripts/util/ui/phone_rankboardfrm.lua ^
../data/scripts/util/ui/phone_rankboardfrm_randommap.lua ^
../data/scripts/util/ui/phone_pvpfrm_rankboard.lua ^
../data/scripts/util/ui/phone_pvpfrm_endless_rankboard.lua ^
../data/scripts/util/ui/phone_toothergamefrm.lua ^
../data/scripts/util/ui/phone_recommandfrm.lua ^
../data/scripts/util/ui/phone_pvparmycardfrm.lua ^
../data/scripts/util/ui/phone_battlerewardfrm.lua ^
../data/scripts/util/ui/phone_savedatafrm.lua ^
../data/scripts/util/ui/phone_systemmailfrm.lua ^
../data/scripts/util/ui/phone_randommapfrm.lua ^
../data/scripts/util/ui/phone_announcementfrm.lua ^
../data/scripts/util/ui/phone_chatmessage_frm.lua ^
../data/scripts/util/ui/phone_myvip_1211.lua ^
../data/scripts/util/ui/phone_playerlistfrm.lua ^
../data/scripts/util/ui/phone_mapinfofrm.lua ^
../data/scripts/util/ui/phone_netshopex.lua ^
../data/scripts/util/ui/phone_netshopfrm.lua ^
../data/scripts/util/ui/phone_selectedhero.lua ^
../data/scripts/util/ui/phone_selectlevel_question.lua ^
../data/scripts/util/ui/phone_webviewnews.lua ^
../data/scripts/util/ui/phone_playcardfrm.lua ^
../data/scripts/util/ui/tanktipfrm.lua ^
../data/scripts/util/ui/tacticstipfrm.lua ^
../data/scripts/util/ui/phone_worldrank.lua ^
../data/scripts/util/ui/sysmenunew.lua ^
../data/scripts/util/ui/syncdatafrm.lua ^
../data/scripts/util/ui/inputfrm.lua ^
../data/scripts/util/ui/phone_gametempbag.lua ^
../data/scripts/util/ui/screenfloatnumber.lua ^
../data/scripts/util/ui/phone_herocardinfofrm.lua ^
../data/scripts/util/ui/phone_skillupfrm.lua ^
../data/scripts/util/ui/phone_skillupfrminmap.lua ^
../data/scripts/util/ui/phone_levelupfrm.lua ^
../data/scripts/util/ui/phone_tankbillboardfrm.lua ^
../data/scripts/util/ui/achievementmanager.lua ^
../data/scripts/util/ui/endingaction.lua ^
../data/scripts/util/ui/pop_up_frm.lua ^
../data/scripts/util/ui/rewardpreviewfrm.lua ^
../data/scripts/util/ui/chariotconfigfrm.lua ^
../data/scripts/util/ui/phone_treasure_frm.lua ^
../data/scripts/util/ui/loadingeffectfrm.lua ^
../data/scripts/util/ui/reviewloginfrm.lua ^
../data/scripts/util/ui/continuouskillingsystem.lua ^
../data/scripts/util/ui/sharefrm.lua ^
../data/scripts/util/ui/aurafrm.lua ^
../data/scripts/util/ui/blackdragonfrm.lua ^
../data/scripts/util/ui/phone_chestfrm.lua ^
../data/scripts/util/ui/phone_userdefmapfrm.lua ^
../data/scripts/util/ui/phone_userdefmapfrm_vert.lua ^
../data/scripts/util/ui/phone_tankavaterfrm.lua ^
../data/scripts/util/ui/gmcheatmanager.lua ^
../data/scripts/util/ui/behaviorstatisticsfrm.lua ^
../data/scripts/game_gopher.lua ^
../data/scripts/util/ui/amulockfrm.lua ^
../data/scripts/dealwith_unit_event.lua ^
../data/scripts/game_start.lua ^
../data/scripts/game_start_special_event.lua ^
../data/scripts/util/ui/barragefrm.lua ^
../data/scripts/util/ui/commentfrm.lua ^
sys/load_end.lua
echo f|xcopy ..\data\tabs\tab_string_jp.lua ..\data\jp.lan /y
echo f|xcopy ..\data\tabs\tab_string.lua ..\data\default.lan /y
echo f|xcopy ..\data\tabs\tab_string_en.lua ..\data\en.lan /y

luac -o ../data/bats.so ^
../data/tabs/model/tab_model.lua ^
../data/tabs/model/tab_model_unit.lua ^
../data/tabs/model/tab_model_effect.lua ^
../data/tabs/model/tab_model_sceobj.lua ^
../data/tabs/model/tab_model_ui.lua ^
../data/tabs/model/tab_model_icon.lua ^
../data/tabs/tab_effect.lua ^
../data/tabs/tab_slash.lua ^
../data/tabs/tab_skill.lua ^
../data/tabs/tab_unit.lua ^
../data/tabs/tab_tactics.lua ^
../data/tabs/tab_army.lua ^
../data/tabs/tab_item.lua ^
../data/tabs/tab_enhance.lua ^
../data/tabs/tab_drop.lua ^
../data/tabs/tab_shopitem.lua ^
../data/tabs/tab_medal.lua ^
../data/tabs/tab_pvpset.lua ^
../data/tabs/tab_bfenv.lua ^
../data/tabs/tab_map.lua ^
../data/tabs/tab_chapter.lua ^
../data/tabs/tab_randmap.lua ^
../data/tabs/tab_shop.lua ^
../data/tabs/tab_sceneobj.lua ^
../data/tabs/tab_treasure.lua ^
../data/tabs/tab_filtertext.lua ^
../data/tabs/tab_chest.lua ^
../data/tabs/tab_task.lua ^
../data/tabs/tab_aura.lua ^
../data/tabs/tab_chariottalent.lua ^
../data/tabs/tab_roleicon.lua ^
../data/tabs/tab_roleborder.lua ^
../data/tabs/tab_rolechampion.lua ^
../data/tabs/tab_avater.lua ^
../data/tabs/tab_mapbehavior.lua ^
sys/init_tabs.lua

luac -o ../data/plus.so ../data/scripts/plus.lua

luac -o ../data/game_up.ss ../data/game_up.ss
echo ´ò°ü.o... ok!
