--------------------------------
--任务（新）
--------------------------------

if not hVar.tab_stringTask then
	hVar.tab_stringTask = {}	--任务（新）
end
local _tab_stringTask = hVar.tab_stringTask


--每日任务
_tab_stringTask[100] = "每日分享"
_tab_stringTask[101] = "矿山巨兽Ⅰ"
_tab_stringTask[102] = "矿山巨兽Ⅱ"
_tab_stringTask[103] = "矿山巨兽Ⅲ"
_tab_stringTask[104] = "矿山巨兽Ⅳ"
_tab_stringTask[105] = "母舰Ⅰ"
_tab_stringTask[106] = "母舰Ⅱ"
_tab_stringTask[107] = "母舰Ⅲ"
_tab_stringTask[108] = "母舰Ⅳ"
_tab_stringTask[109] = "异虫Ⅰ"
_tab_stringTask[110] = "异虫Ⅱ"
_tab_stringTask[111] = "异虫Ⅲ"
_tab_stringTask[112] = "异虫Ⅳ"
_tab_stringTask[113] = "魔眼Ⅰ"
_tab_stringTask[114] = "魔眼Ⅱ"
_tab_stringTask[115] = "魔眼Ⅲ"
_tab_stringTask[116] = "魔眼Ⅳ"
_tab_stringTask[117] = "空中堡垒Ⅰ"
_tab_stringTask[118] = "空中堡垒Ⅱ"
_tab_stringTask[119] = "空中堡垒Ⅲ"
_tab_stringTask[120] = "空中堡垒Ⅳ"
_tab_stringTask[121] = "弧反应堆Ⅰ"
_tab_stringTask[122] = "弧反应堆Ⅱ"
_tab_stringTask[123] = "弧反应堆Ⅲ"
_tab_stringTask[124] = "弧反应堆Ⅳ"
_tab_stringTask[201] = "矿山巨兽Ⅰ"
_tab_stringTask[202] = "矿山巨兽Ⅱ"
_tab_stringTask[203] = "矿山巨兽Ⅲ"
_tab_stringTask[204] = "矿山巨兽Ⅳ"
_tab_stringTask[205] = "母舰Ⅰ"
_tab_stringTask[206] = "母舰Ⅱ"
_tab_stringTask[207] = "母舰Ⅲ"
_tab_stringTask[208] = "母舰Ⅳ"
_tab_stringTask[209] = "异虫Ⅰ"
_tab_stringTask[210] = "异虫Ⅱ"
_tab_stringTask[211] = "异虫Ⅲ"
_tab_stringTask[212] = "异虫Ⅳ"
_tab_stringTask[213] = "魔眼Ⅰ"
_tab_stringTask[214] = "魔眼Ⅱ"
_tab_stringTask[215] = "魔眼Ⅲ"
_tab_stringTask[216] = "魔眼Ⅳ"
_tab_stringTask[217] = "空中堡垒Ⅰ"
_tab_stringTask[218] = "空中堡垒Ⅱ"
_tab_stringTask[219] = "空中堡垒Ⅲ"
_tab_stringTask[220] = "空中堡垒Ⅳ"
_tab_stringTask[221] = "弧反应堆Ⅰ"
_tab_stringTask[222] = "弧反应堆Ⅱ"
_tab_stringTask[223] = "弧反应堆Ⅲ"
_tab_stringTask[224] = "弧反应堆Ⅳ"
_tab_stringTask[301] = "刷新商店"
_tab_stringTask[311] = "武器宝箱"
_tab_stringTask[321] = "战术宝箱"
_tab_stringTask[331] = "宠物宝箱"
_tab_stringTask[341] = "装备宝箱"
_tab_stringTask[351] = "击杀敌人"
_tab_stringTask[352] = "击杀敌人"
_tab_stringTask[353] = "击杀敌人"
_tab_stringTask[361] = "击杀BOSS"
_tab_stringTask[362] = "击杀BOSS"
_tab_stringTask[363] = "击杀BOSS"
_tab_stringTask[371] = "使用战术卡"
_tab_stringTask[372] = "使用战术卡"
_tab_stringTask[373] = "使用战术卡"
_tab_stringTask[381] = "营救工程师"
_tab_stringTask[382] = "营救工程师"
_tab_stringTask[383] = "营救工程师"
_tab_stringTask[391] = "前哨阵地"
_tab_stringTask[392] = "前哨阵地"
_tab_stringTask[393] = "前哨阵地"
_tab_stringTask[401] = "天梯迷宫"
_tab_stringTask[402] = "天梯迷宫"
_tab_stringTask[403] = "天梯迷宫"
_tab_stringTask[404] = "天梯迷宫"
_tab_stringTask[411] = "战车损坏"
_tab_stringTask[412] = "战车损坏"
_tab_stringTask[413] = "战车损坏"
_tab_stringTask[421] = "宠物跟随"
_tab_stringTask[422] = "宠物跟随"
_tab_stringTask[423] = "宠物跟随"
_tab_stringTask[431] = "改造装备"
_tab_stringTask[432] = "改造装备"
_tab_stringTask[433] = "改造装备"
_tab_stringTask[441] = "升级战术卡"
_tab_stringTask[442] = "升级战术卡"
_tab_stringTask[443] = "升级战术卡"
_tab_stringTask[451] = "升级枪塔"
_tab_stringTask[452] = "升级枪塔"
_tab_stringTask[453] = "升级枪塔"
_tab_stringTask[461] = "升级宠物"
_tab_stringTask[462] = "升级宠物"
_tab_stringTask[463] = "升级宠物"
_tab_stringTask[501] = "母巢之战"
_tab_stringTask[502] = "母巢之战"
_tab_stringTask[503] = "母巢之战"
_tab_stringTask[521] = "夺宝奇兵"
_tab_stringTask[522] = "夺宝奇兵"
_tab_stringTask[523] = "夺宝奇兵"



--周任务
_tab_stringTask[1001] = "武器宝箱"
_tab_stringTask[1002] = "战术宝箱"
_tab_stringTask[1003] = "宠物宝箱"
_tab_stringTask[1004] = "装备宝箱"
_tab_stringTask[1005] = "击杀敌人"
_tab_stringTask[1006] = "营救工程师"
_tab_stringTask[1007] = "战车损坏"
_tab_stringTask[1008] = "前哨阵地"
_tab_stringTask[1009] = "天梯迷宫"
_tab_stringTask[1010] = "击杀BOSS"
_tab_stringTask[1011] = "使用战术卡"
_tab_stringTask[1012] = "宠物跟随"
_tab_stringTask[1013] = "改造装备"
_tab_stringTask[1014] = "升级战术卡"
_tab_stringTask[1015] = "升级枪塔"
_tab_stringTask[1016] = "升级宠物"
_tab_stringTask[1017] = "母巢之战"
_tab_stringTask[1018] = "夺宝奇兵"
